name: 'Find Python Projects'
description: 'TODO Description'

inputs:
  root-path:
    description: 'TODO Description'
    required: false
    default: ''

outputs:
  projects:
    description: 'TODO'

  paths:
    description: 'TODO: JSON array of projects paths'

  testable-projects:
    description: 'TODO'

runs:
  using: 'node16'
  main: 'dist/index.js'
