name: Find Python Projects
description: Discover Python projects in a repository and expose helpful things from pyproject.toml to other steps
author: brandonlwhite@gmail.com
branding:
  icon: search
  color: blue

inputs:
  root-dir:
    description: Directory root for where to begin recursively searching for projects.  Python projects contained in this directory or lower will be discovered.
    required: false
    default: "."
  additional-export-paths:
    description: Additional TOML keys to export as part of the projects object. Specify them as json path strings, separated by commas. For example, "tool.upside.foo,bar.baz".
    required: false
    default: ""

outputs:
  paths:
    description: JSON array of found project path strings

  projects:
    description: JSON array of all found projects (`project` object)

  testable-projects:
    description: JSON array of all found projects (`project` object) that implement a `test` command

  packageable-projects:
    description: JSON array of all found projects (`project` object) that implement a `package` command

runs:
  using: "node20"
  main: "dist/index.js"
