name: Example Workflow
on:
  pull_request
jobs:
  discover-python-projects:
    name: Discover projects
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Discover Projects
        id: discover
        uses: BrandonLWhite/find-python-projects-action@vX.Y.Z

      - name: Print Paths
        run: echo ${{steps.discover.outputs.paths }}

    outputs:
      projects-by-command: ${{ steps.discover.outputs.projects-by-command }}

  build-python-projects:
    name: "Test: ${{ matrix.project.name }}"
    runs-on: ubuntu-latest
    needs: discover-python-projects
    strategy:
      matrix:
        project: ${{ fromJson(needs.discover-python-projects.outputs.projects-by-command).install }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.project.directory }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Dump project object
        run: |
          echo '${{ toJson(matrix.project) }}'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ matrix.project.path }}

      - name: Install project
        if: matrix.project.commands.install
        run: ${{ matrix.project.commands.install }}

      - name: Test project
        run: ${{ matrix.project.commands.test }}

      - name: Package project
        if: matrix.project.commands.package
        run: ${{ matrix.project.commands.package }}
